### PR TITLE
Add 'TIMEOUT' test result state

### PR DESCRIPTION
**Pull request by brianhlin**

### CODE REVIEW

**Comment by edquist** [comment]
Neat, looks good.  Should we update `core.diagnose` also?

**Comment by brianhlin** [comment]
Update it how? Like changing the `EXIT STATUS` if it's `-1` to indicate a timeout?

**Comment by edquist** [comment]
Yeah; so does anything parse the `EXIT STATUS:` line?  Or is it just for human inspection?  (I didn't see anything in osg-test or vm-test-runs that looks like it parses the string `EXIT STATUS`)

If it's just for human inspection, then the the format doesn't matter too much; the idea was just to make it a bit more obvious that the timeout was hit.  Maybe something like `EXIT STATUS: -1 (command timed out)`.  But if that breaks anything else that parses it then maybe something else would work.

**Comment by brianhlin** [comment]
You're correct, nothing in osg-test or vm-test-runs parses the output of
core.diagnose(). I'll submit another PR for the message.

**Pull request merged**
