### PR TITLE
Add timeout message to logs when diagnosing command results

### PR DESCRIPTION
**Pull request by brianhlin**

### CODE REVIEW

**Comment by brianhlin** [comment]
Hey @edquist, did you miss this? Have any questions/comments?

**Comment by edquist** [comment]
Oh hey @brianhlin, thanks for the ping on this.  So, what you have looks like it should work fine.  My only thoughts are, in case we ever want to do more with `status` in `core.diagnose`, maybe it would be better to keep it as just the int value instead of sometimes an int or sometimes a string message.

Eg, something like this might be slightly longer, but it keeps `status` intact:

```
    if status == -1:
        result += 'EXIT STATUS: %d (command timed out)\n' % (status)
    else
        result += 'EXIT STATUS: %d\n' % (status)
```

Nevertheless I'm not the osg-test maintainer - if you'd like to just stick with what you've got that's fine too; let me know and I'll merge it into my PR.

**Comment by brianhlin** [comment]
My old commit did leave status intact but your method is certainly clearer. I did write something like that to begin with but didn't like it at the time. It's a new day though and I think this is cleaner now so I've updated the PR!

**Comment by edquist** [comment]
LGTM!

**Pull request merged**
